# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shop_pb2 as shop__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PurchaseItem = channel.unary_unary(
                '/shop.ShopService/PurchaseItem',
                request_serializer=shop__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=shop__pb2.PurchaseResponse.FromString,
                _registered_method=True)
        self.MakePayment = channel.unary_unary(
                '/shop.ShopService/MakePayment',
                request_serializer=shop__pb2.PaymentRequest.SerializeToString,
                response_deserializer=shop__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/shop.ShopService/PlaceOrder',
                request_serializer=shop__pb2.OrderRequest.SerializeToString,
                response_deserializer=shop__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetProductInfo = channel.unary_unary(
                '/shop.ShopService/GetProductInfo',
                request_serializer=shop__pb2.ProductInfoRequest.SerializeToString,
                response_deserializer=shop__pb2.ProductInfoResponse.FromString,
                _registered_method=True)


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PurchaseItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Nuevo servicio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PurchaseItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseItem,
                    request_deserializer=shop__pb2.PurchaseRequest.FromString,
                    response_serializer=shop__pb2.PurchaseResponse.SerializeToString,
            ),
            'MakePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePayment,
                    request_deserializer=shop__pb2.PaymentRequest.FromString,
                    response_serializer=shop__pb2.PaymentResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=shop__pb2.OrderRequest.FromString,
                    response_serializer=shop__pb2.OrderResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=shop__pb2.ProductInfoRequest.FromString,
                    response_serializer=shop__pb2.ProductInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PurchaseItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.ShopService/PurchaseItem',
            shop__pb2.PurchaseRequest.SerializeToString,
            shop__pb2.PurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.ShopService/MakePayment',
            shop__pb2.PaymentRequest.SerializeToString,
            shop__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.ShopService/PlaceOrder',
            shop__pb2.OrderRequest.SerializeToString,
            shop__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.ShopService/GetProductInfo',
            shop__pb2.ProductInfoRequest.SerializeToString,
            shop__pb2.ProductInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
